name: build
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main

jobs:
  build:
    runs-on: windows-2019 

    name: Install Zig 
    steps:
      - uses: actions/checkout@v3
      - name: Install zig 
        shell: bash
        run: |
          ./installzig.ps1
 

